server {
    listen 80;
    server_name localhost;

    # Hướng luồng cho API (Backend)
    location /api/ {
        proxy_pass http://c2:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Hướng luồng cho Giao diện (Frontend)
    location / {
        proxy_pass http://c1:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}