server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # Chỗ này để dự phòng nếu muốn c1 gọi thẳng c2 mà không qua c9
    location /api/ {
        proxy_pass http://c2:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}