server {
    listen 80;
    
    # Đưa root ra ngoài để áp dụng cho TẤT CẢ các location (bao gồm cả regex bên dưới)
    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        # Dòng quan trọng cho React Router (SPA):
        try_files $uri $uri/ /index.html;
    }

    # Cấu hình cache cho file tĩnh (js, css, ảnh) để web load nhanh
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires 1y;
        add_header Pragma public;
        add_header Cache-Control "public";
    }
}